world df_ops {
  // Representing a dataframe as a handle
  type dataframe = handle;  

  // Functions to create and manipulate data formats and dataframes
  export create_format_from_string: func(data_str: string) -> result<format, string>;
  
  export create_dataframe_from_format: func(data_format: format) -> result<dataframe, string>;

  //  DataFrame Operations
  export add_log_column: func(df: dataframe, column_name: string) -> result<dataframe, string>;

  export calculate_means: func(df: dataframe) -> result<string, string>;  ;; Returns JSON string of column means

  export multiply_dataframe: func(df: dataframe, factor: float64) -> result<dataframe, string>;

  export read_dataframe: func(path: string) -> result<dataframe, string>;  ;; Creates dataframe from given path
}
